name: CI

on:
  push:
    branches:
      - main
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Clone dangerous repo
      run: git clone https://github.com/juice-shop/juice-shop.git app
    - name: Run gitleaks
      run: >
           docker run
           -v ${PWD}/app:/app
           zricethezav/gitleaks:latest
           --path="/app" 
           --report=/app/gitleaks.report
    - name: Echo report
      run: cat app/gitleaks.report
      if: ${{ failure() }}